### ISSUE TITLE
问下config.h的创建步骤

### ISSUE THREAD

**Issue by wosilove** [yingmu52/Telegram#2]
我下载了源码，按照[Add readme.md #221](https://github.com/peter-iakovlev/Telegram/pull/221/files)进行操作。
第三步 **Creat a new head file named config（Telegraph->New File->Header File）** 创建完成以后还是不能够成功。不知道为什么，想问下您当时是怎么创建的config.h？

**Comment by yingmu52** [comment]
你不需要创建。已经创建好了


Sent from my iPhone

On May 31, 2018, at 7:52 PM, Rick_rui <notifications@github.com<mailto:notifications@github.com>> wrote:


我下载了源码，按照Add readme.md #221<https://github.com/peter-iakovlev/Telegram/pull/221/files>进行操作。
第三步 Creat a new head file named config（Telegraph->New File->Header File） 创建完成以后还是不能够成功。不知道为什么，想问下您当时是怎么创建的config.h？

**Comment by wosilove** [comment]
@yingmu52 我看了一下的你源码[TGShareContextSignal.m](https://github.com/yingmu52/Telegram/blob/public/LegacyDatabase/TGShareContextSignal.m)#import "../../config.h"，你将../../去掉了

**Comment by yingmu52** [comment]
你在项目里搜不到config.h吗


Sent from my iPhone

On May 31, 2018, at 8:02 PM, Rick_rui <notifications@github.com<mailto:notifications@github.com>> wrote:


@yingmu52<https://github.com/yingmu52> 我看了一下的你源码TGShareContextSignal.m<https://github.com/yingmu52/Telegram/blob/public/LegacyDatabase/TGShareContextSignal.m>#import "../../config.h"，你将../../去掉了

**Comment by wosilove** [comment]
@yingmu52 我看到了config.h，我是想自己尝试着用源码运行一下，然后看看能不能成功。已经解决了。config.h的问题。
问下您那边可以在真机上面运行了吗？

**Comment by yingmu52** [comment]
之前腾讯的一个朋友在真机上跑了起来，我自己没测试过。

Sent from my iPhone

On May 31, 2018, at 8:02 PM, Rick_rui <notifications@github.com<mailto:notifications@github.com>> wrote:


@yingmu52<https://github.com/yingmu52> 我看了一下的你源码TGShareContextSignal.m<https://github.com/yingmu52/Telegram/blob/public/LegacyDatabase/TGShareContextSignal.m>#import "../../config.h"，你将../../去掉了
